const data = [
    { 
        href: "",
        src: "/img/01.PNG",
        type: "웹사이트",
        title: "전소영 포트폴리오 웹 사이트",
        contents: "내용무",
        refer: "HTML / CSS / JavaScript(ES6)",
    },
    { 
        href: "",
        src: "/img/13.PNG",
        type: "웹사이트",
        title: "MOYAM",
        contents: "내용무",
        refer: "Vue / Vuetify / CSS",
    },
    { 
        src: "/img/01.PNG",
        type: "특집기사",
        title: "아동성범죄 향한 무딘 칼날",
        contents: "냉무",
        refer: "HTML / CSS / jQuery",
    },
    { 
        src: "/img/02.PNG",
        type: "특집기사",
        title: "퍼져나가는 '후쿠시마산'의 공포",
        contents: "계산기",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/03.PNG",
        type: "특집기사",
        title: "데이터로 보는 부동산 시장",
        contents: "CSS fixed",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    {
        src: "/img/04.PNG",
        type: "특집기사",
        title: "'폭식', 미국과 인류의 목을 조르다",
        contents: "CSS fixed",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/05.PNG",
        type: "특집기사",
        title: "누가 그들을 죽음으로 내몰았는가",
        contents: "탭",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/06.PNG",
        type: "특집기사",
        title: "나는 치매 환자 입니다",
        contents: "플러그인",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/07.PNG",
        type: "특집기사",
        title: "산불의 계절이 돌아왔다",
        contents: "플러그인",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/08.PNG",
        type: "특집기사",
        title: "고독사, 그들이 살던 세상",
        contents: "플러그인",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/09.PNG",
        type: "특집기사",
        title: "뷰티아웃사이드, '스펙안에 성형있다'",
        contents: "??",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/10.PNG",
        type: "특집기사",
        title: "'윤창호 사건' 1년, 만취한 대한민국 도로",
        contents: "??",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/11.PNG",
        type: "특집기사",
        title: "반려동물의 차량 안전, 사람만큼 중요하다",
        contents: "??",
        refer: "HTML / CSS / jQuery / 반응형",
    },
    { 
        src: "/img/12.PNG",
        type: "개인 프로젝트",
        title: "대한민국 축구, 내맘대로 포메이션",
        contents: "드래그앤드롭",
        refer: "HTML / CSS / jQuery",
    },
]